### PR TITLE
correctly fetches name if a version > 40 was used to parse the AST

### PR DESCRIPTION
**Pull request by krageon**
after this version, Decl nodes are no longer generated.

### CODE REVIEW

**Comment by krageon** [comment]
This is the only issue that really popped out at me when I was parsing using version 50.

**Comment by tpunt** [comment]
There's a few problems with this PR with respect to handling anonymous classes. Explicitly checking for a `null` return in `getNodeName` should resolve this:
```
     private function getNodeName(Node $node) : string
     {
         if ($node instanceof Decl) {
-            return $node->name;
+            return $node->name ?? '';
         }
 
-        return $node->children['name'];
+        return $node->children['name'] ?? '';
     }
```

Also, remember to import the `Decl` class at the top:
```
 use ast\Node;
+use ast\Node\Decl;
```

I'll merge this once these changes have been made.

**Comment by tpunt** [comment]
I've made the necessary changes to your patch. Thanks!

**Comment by krageon** [comment]
Ah, thank you very much! :)

**Pull request closed without merging**
